### ISSUE TITLE
error: jsonrpc error: Parse error: invalid type: integer 

### ISSUE THREAD

**Issue by Nathanofzion** [stellar/soroban-dapps-challenge#88]
### What version are you using?

Soroban cli 20.1.1
Node js v18.0.0
Npm 8.5.5

### What did you do?
npm run setup

### What did you expect to see?

Contract deployed successfully with ID: CBXHU5BWWTOCZRYX3DMSSKCFG7B3K2YG2I5F75ALPQ6GCY6ZES2XKLTI
Deploy the crowdfund contract
Contract deployed successfully with ID: CBKY7UN5VGD4LIQFOBOTSUSQWK67BZZTA23NIEVWSWRR5SAT26JQN2BN
Initialize the abundance token contract

Initialize the crowdfund contract

Done

> soroban-example-dapp@0.1.0 build-contracts
...

### What did you see instead?

-rwxr-xr-x@ 1 *my username*  staff  7799 Jan  7 19:17 abundance_token.wasm
-rwxr-xr-x@ 1 *my username*  staff  10920 Jan  7 20:01 soroban_crowdfund_contract.wasm
Deploy the abundance token contract
error: jsonrpc error: Parse error: invalid type: integer `142503`, expected a string at line 1 column 229

**Comment by Julian-dev28** [comment]
Closing because the issue was resolved in commit: https://github.com/stellar/soroban-dapps-challenge/commit/d03beb0451ed38770f6f334809cd83a414682729
